# Generated by Django 4.1.2 on 2022-10-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendent',
            name='storage_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
